### ISSUE TITLE
Constant Contact API

### ISSUE THREAD

**Issue by deadlyraptor** [deadlyraptor/contact-copy#3]
Ideally, the script could interact with the Constant Contact API and automatically upload the new contacts instead of having to manually copy from the new workbook.

There is no official Python wrapper.

**Comment by jmr0** [comment]
Whenever you decide to tackle this, highly recommend http://docs.python-requests.org/en/master/ - it'll cut down a lot of the boilerplate you have to deal with using Python's native libraries

**Comment by deadlyraptor** [comment]
Thanks, @jmr0. This is a generic wrapper for the Python HTTP libraries? I've seen it mentioned elsewhere so I'll definitely make use of it.

My desire to switch to MailChimp grows, though, because they have an official Python wrapper.

**Comment by jmr0** [comment]
Correct. MailChimp seems like a solid product, but having a Python API shouldn't be the main reason to switch :)

**Comment by deadlyraptor** [comment]
https://community.constantcontact.com/t5/Documentation/Authentication-using-OAuth-2-0-Server-and-Client-Flows/ba-p/38313
